# Generated by Django 4.0.5 on 2022-06-30 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 1, 18, 162793, tzinfo=utc), verbose_name=datetime.datetime(2022, 6, 30, 5, 1, 18, 162793, tzinfo=utc)),
        ),
    ]
