# Generated by Django 4.0.5 on 2022-06-30 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_homework_pub_date_homework_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='date',
        ),
        migrations.AddField(
            model_name='homework',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 2, 45, 475347, tzinfo=utc), verbose_name=datetime.datetime(2022, 6, 30, 5, 2, 45, 475347, tzinfo=utc)),
        ),
    ]
