# Generated by Django 4.0.5 on 2022-06-30 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_homework_date_homework_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 3, 20, 838164, tzinfo=utc), verbose_name=datetime.datetime(2022, 6, 30, 5, 3, 20, 838164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 3, 20, 838164, tzinfo=utc), verbose_name=datetime.datetime(2022, 6, 30, 5, 3, 20, 838164, tzinfo=utc)),
        ),
    ]
