# Generated by Django 4.0.5 on 2022-06-30 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_homework_pub_date_alter_homework_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 6, 15, 738953, tzinfo=utc), verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homework',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 6, 15, 738953, tzinfo=utc), verbose_name=django.utils.timezone.now),
        ),
    ]
