# Generated by Django 4.0.5 on 2022-06-30 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_homework_pub_date_alter_homework_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 8, 13, 227953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 5, 8, 13, 227953, tzinfo=utc)),
        ),
    ]
