# Generated by Django 4.0.5 on 2022-06-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_homework_pub_date_alter_homework_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
